version: '3.8'

services:
  # 后端 API 服务
  backend:
    build:
      context: ./word-wonderland-backend
      dockerfile: Dockerfile
    container_name: word-wonderland-backend
    ports:
      - "3000:3000"
    volumes:
      # 使用命名存储卷持久化数据（推荐用于生产环境）
      - backend-data:/app/data
      # 或使用绑定挂载（便于直接访问文件）：
      # - ./word-wonderland-backend/data:/app/data
    restart: unless-stopped
    networks:
      - word-wonderland-network

  # 管理员后台
  admin:
    build:
      context: ./word-wonderland-admin
      dockerfile: Dockerfile
    container_name: word-wonderland-admin
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - word-wonderland-network

  # 学生端应用
  app:
    build:
      context: ./word-wonderland-app
      dockerfile: Dockerfile
    container_name: word-wonderland-app
    ports:
      - "5174:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - word-wonderland-network

networks:
  word-wonderland-network:
    driver: bridge

volumes:
  # 命名存储卷 - 用于持久化后端数据
  backend-data:
    driver: local

